// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exams/test/presentation/auth/login/view_models/login_view_model/login_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_online_exams/api/model/saved_user_credentials_model.dart'
    as _i2;
import 'package:elevate_online_exams/core/api_result/api_result.dart' as _i5;
import 'package:elevate_online_exams/domain/model/login_model.dart' as _i6;
import 'package:elevate_online_exams/domain/model/request_model/login_request_model.dart'
    as _i7;
import 'package:elevate_online_exams/domain/usecase/load_saved_user_credentials_use_case.dart'
    as _i9;
import 'package:elevate_online_exams/domain/usecase/login_use_case.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSavedUserCredentialsModel_0 extends _i1.SmartFake
    implements _i2.SavedUserCredentialsModel {
  _FakeSavedUserCredentialsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.LoginModel>> call(
    _i7.LoginRequestModel? loginRequestModel, {
    required bool? isCheckedRememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [loginRequestModel],
              {#isCheckedRememberMe: isCheckedRememberMe},
            ),
            returnValue: _i4.Future<_i5.ApiResult<_i6.LoginModel>>.value(
              _i8.dummyValue<_i5.ApiResult<_i6.LoginModel>>(
                this,
                Invocation.method(
                  #call,
                  [loginRequestModel],
                  {#isCheckedRememberMe: isCheckedRememberMe},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.LoginModel>>);
}

/// A class which mocks [LoadSavedUserCredentialsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadSavedUserCredentialsUseCase extends _i1.Mock
    implements _i9.LoadSavedUserCredentialsUseCase {
  MockLoadSavedUserCredentialsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SavedUserCredentialsModel> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.SavedUserCredentialsModel>.value(
              _FakeSavedUserCredentialsModel_0(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i2.SavedUserCredentialsModel>);
}
