// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exams/test/api/datasource/subject_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:elevate_online_exams/api/model/request/change_password_request_dto/change_password_request_dto.dart'
    as _i16;
import 'package:elevate_online_exams/api/model/request/edit_profile_request_dto/edit_profile_request_dto.dart'
    as _i15;
import 'package:elevate_online_exams/api/model/request/forget_password_request_dto/forget_password_request_dto.dart'
    as _i17;
import 'package:elevate_online_exams/api/model/request/login_request_dto/login_request_dto.dart'
    as _i14;
import 'package:elevate_online_exams/api/model/request/register_request_dto/register_request_dto.dart'
    as _i13;
import 'package:elevate_online_exams/api/model/request/reset_password_request_dto/reset_password_request_dto.dart'
    as _i19;
import 'package:elevate_online_exams/api/model/request/verify_reset_code_request_dto/verify_reset_code_request_dto.dart'
    as _i18;
import 'package:elevate_online_exams/api/model/response/change_password_response/change_password_response_dto.dart'
    as _i7;
import 'package:elevate_online_exams/api/model/response/edit_profile_response/edit_profile_response.dart'
    as _i6;
import 'package:elevate_online_exams/api/model/response/forget_password_response/forget_password_response_dto.dart'
    as _i8;
import 'package:elevate_online_exams/api/model/response/login_response.dart'
    as _i3;
import 'package:elevate_online_exams/api/model/response/register_response.dart'
    as _i2;
import 'package:elevate_online_exams/api/model/response/reset_password_response/reset_password_response_dto.dart'
    as _i10;
import 'package:elevate_online_exams/api/model/response/subject_exams_response/subject_exams_response.dart'
    as _i5;
import 'package:elevate_online_exams/api/model/response/subject_response/subject_response.dart'
    as _i4;
import 'package:elevate_online_exams/api/model/response/verify_reset_code_response/verify_reset_code_response_dto.dart'
    as _i9;
import 'package:elevate_online_exams/api/web_services/web_services.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponse_0 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubjectResponse_2 extends _i1.SmartFake
    implements _i4.SubjectResponse {
  _FakeSubjectResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubjectExamsResponse_3 extends _i1.SmartFake
    implements _i5.SubjectExamsResponse {
  _FakeSubjectExamsResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEditProfileResponse_4 extends _i1.SmartFake
    implements _i6.EditProfileResponse {
  _FakeEditProfileResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_5 extends _i1.SmartFake
    implements _i7.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_6 extends _i1.SmartFake
    implements _i8.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseDto_7 extends _i1.SmartFake
    implements _i9.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_8 extends _i1.SmartFake
    implements _i10.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WebServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebServices extends _i1.Mock implements _i11.WebServices {
  MockWebServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.RegisterResponse> register(
    _i13.RegisterRequestDto? registerRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequestDto]),
            returnValue: _i12.Future<_i2.RegisterResponse>.value(
              _FakeRegisterResponse_0(
                this,
                Invocation.method(#register, [registerRequestDto]),
              ),
            ),
          )
          as _i12.Future<_i2.RegisterResponse>);

  @override
  _i12.Future<_i3.LoginResponse> login(_i14.LoginRequestDto? loginRequestDto) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestDto]),
            returnValue: _i12.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [loginRequestDto]),
              ),
            ),
          )
          as _i12.Future<_i3.LoginResponse>);

  @override
  _i12.Future<_i4.SubjectResponse> getAllSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, []),
            returnValue: _i12.Future<_i4.SubjectResponse>.value(
              _FakeSubjectResponse_2(
                this,
                Invocation.method(#getAllSubjects, []),
              ),
            ),
          )
          as _i12.Future<_i4.SubjectResponse>);

  @override
  _i12.Future<_i5.SubjectExamsResponse> getAllSubjectExams(String? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjectExams, [subjectId]),
            returnValue: _i12.Future<_i5.SubjectExamsResponse>.value(
              _FakeSubjectExamsResponse_3(
                this,
                Invocation.method(#getAllSubjectExams, [subjectId]),
              ),
            ),
          )
          as _i12.Future<_i5.SubjectExamsResponse>);

  @override
  _i12.Future<_i6.EditProfileResponse> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i12.Future<_i6.EditProfileResponse>.value(
              _FakeEditProfileResponse_4(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i12.Future<_i6.EditProfileResponse>);

  @override
  _i12.Future<_i6.EditProfileResponse> editProfile(
    _i15.EditProfileRequestDto? editProfileRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [editProfileRequestDto]),
            returnValue: _i12.Future<_i6.EditProfileResponse>.value(
              _FakeEditProfileResponse_4(
                this,
                Invocation.method(#editProfile, [editProfileRequestDto]),
              ),
            ),
          )
          as _i12.Future<_i6.EditProfileResponse>);

  @override
  _i12.Future<_i7.ChangePasswordResponseDto> changePassword(
    _i16.ChangePasswordRequestDto? changePasswordRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordRequestDto]),
            returnValue: _i12.Future<_i7.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_5(
                this,
                Invocation.method(#changePassword, [changePasswordRequestDto]),
              ),
            ),
          )
          as _i12.Future<_i7.ChangePasswordResponseDto>);

  @override
  _i12.Future<_i8.ForgetPasswordResponseDto> forgetPassword(
    _i17.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestDto]),
            returnValue: _i12.Future<_i8.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_6(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequestDto]),
              ),
            ),
          )
          as _i12.Future<_i8.ForgetPasswordResponseDto>);

  @override
  _i12.Future<_i9.VerifyResetCodeResponseDto> verifyResetCode(
    _i18.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestDto]),
            returnValue: _i12.Future<_i9.VerifyResetCodeResponseDto>.value(
              _FakeVerifyResetCodeResponseDto_7(
                this,
                Invocation.method(#verifyResetCode, [
                  verifyResetCodeRequestDto,
                ]),
              ),
            ),
          )
          as _i12.Future<_i9.VerifyResetCodeResponseDto>);

  @override
  _i12.Future<_i10.ResetPasswordResponseDto> resetPassword(
    _i19.ResetPasswordRequestDto? resetPasswordRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestDto]),
            returnValue: _i12.Future<_i10.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_8(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequestDto]),
              ),
            ),
          )
          as _i12.Future<_i10.ResetPasswordResponseDto>);
}
