// Mocks generated by Mockito 5.4.6 from annotations
// in elevate_online_exams/test/domain/usecase/reset_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:elevate_online_exams/api/model/saved_user_credentials_model.dart'
    as _i2;
import 'package:elevate_online_exams/core/api_result/api_result.dart' as _i5;
import 'package:elevate_online_exams/domain/model/change_password_model.dart'
    as _i13;
import 'package:elevate_online_exams/domain/model/forget_password_model.dart'
    as _i15;
import 'package:elevate_online_exams/domain/model/login_model.dart' as _i9;
import 'package:elevate_online_exams/domain/model/register_model.dart' as _i6;
import 'package:elevate_online_exams/domain/model/request_model/change_password_request_model.dart'
    as _i14;
import 'package:elevate_online_exams/domain/model/request_model/edit_profile_request_model.dart'
    as _i12;
import 'package:elevate_online_exams/domain/model/request_model/forget_password_request_model.dart'
    as _i16;
import 'package:elevate_online_exams/domain/model/request_model/login_request_model.dart'
    as _i10;
import 'package:elevate_online_exams/domain/model/request_model/register_request_model.dart'
    as _i7;
import 'package:elevate_online_exams/domain/model/request_model/reset_password_request_model.dart'
    as _i20;
import 'package:elevate_online_exams/domain/model/request_model/verify_reset_code_request_model.dart'
    as _i18;
import 'package:elevate_online_exams/domain/model/reset_password_model.dart'
    as _i19;
import 'package:elevate_online_exams/domain/model/user_model.dart' as _i11;
import 'package:elevate_online_exams/domain/model/verify_reset_code_model.dart'
    as _i17;
import 'package:elevate_online_exams/domain/repos/auth_repo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSavedUserCredentialsModel_0 extends _i1.SmartFake
    implements _i2.SavedUserCredentialsModel {
  _FakeSavedUserCredentialsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i3.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.RegisterModel>> register({
    required _i7.RegisterRequestModel? registerRequestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #registerRequestModel: registerRequestModel,
            }),
            returnValue: _i4.Future<_i5.ApiResult<_i6.RegisterModel>>.value(
              _i8.dummyValue<_i5.ApiResult<_i6.RegisterModel>>(
                this,
                Invocation.method(#register, [], {
                  #registerRequestModel: registerRequestModel,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.RegisterModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i9.LoginModel>> login(
    _i10.LoginRequestModel? loginRequestModel, {
    required bool? isCheckedRememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [loginRequestModel],
              {#isCheckedRememberMe: isCheckedRememberMe},
            ),
            returnValue: _i4.Future<_i5.ApiResult<_i9.LoginModel>>.value(
              _i8.dummyValue<_i5.ApiResult<_i9.LoginModel>>(
                this,
                Invocation.method(
                  #login,
                  [loginRequestModel],
                  {#isCheckedRememberMe: isCheckedRememberMe},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i9.LoginModel>>);

  @override
  _i4.Future<_i2.SavedUserCredentialsModel> loadSavedUserCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedUserCredentials, []),
            returnValue: _i4.Future<_i2.SavedUserCredentialsModel>.value(
              _FakeSavedUserCredentialsModel_0(
                this,
                Invocation.method(#loadSavedUserCredentials, []),
              ),
            ),
          )
          as _i4.Future<_i2.SavedUserCredentialsModel>);

  @override
  _i4.Future<_i5.ApiResult<_i11.UserModel>> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i4.Future<_i5.ApiResult<_i11.UserModel>>.value(
              _i8.dummyValue<_i5.ApiResult<_i11.UserModel>>(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i11.UserModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i11.UserModel>> editProfile(
    _i12.EditProfileRequestModel? editProfileRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [editProfileRequestModel]),
            returnValue: _i4.Future<_i5.ApiResult<_i11.UserModel>>.value(
              _i8.dummyValue<_i5.ApiResult<_i11.UserModel>>(
                this,
                Invocation.method(#editProfile, [editProfileRequestModel]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i11.UserModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i13.ChangePasswordModel>> changePassword(
    _i14.ChangePasswordRequestModel? changePasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordRequestModel]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i13.ChangePasswordModel>>.value(
                  _i8.dummyValue<_i5.ApiResult<_i13.ChangePasswordModel>>(
                    this,
                    Invocation.method(#changePassword, [
                      changePasswordRequestModel,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i13.ChangePasswordModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i15.ForgetPasswordModel>> forgetPassword(
    _i16.ForgetPasswordRequestModel? forgetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestModel]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i15.ForgetPasswordModel>>.value(
                  _i8.dummyValue<_i5.ApiResult<_i15.ForgetPasswordModel>>(
                    this,
                    Invocation.method(#forgetPassword, [
                      forgetPasswordRequestModel,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i15.ForgetPasswordModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i17.VerifyResetCodeModel>> verifyResetCode(
    _i18.VerifyResetCodeRequestModel? verifyResetCodeRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestModel]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i17.VerifyResetCodeModel>>.value(
                  _i8.dummyValue<_i5.ApiResult<_i17.VerifyResetCodeModel>>(
                    this,
                    Invocation.method(#verifyResetCode, [
                      verifyResetCodeRequestModel,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i17.VerifyResetCodeModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i19.ResetPasswordModel>> resetPassword(
    _i20.ResetPasswordRequestModel? resetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestModel]),
            returnValue:
                _i4.Future<_i5.ApiResult<_i19.ResetPasswordModel>>.value(
                  _i8.dummyValue<_i5.ApiResult<_i19.ResetPasswordModel>>(
                    this,
                    Invocation.method(#resetPassword, [
                      resetPasswordRequestModel,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i19.ResetPasswordModel>>);
}
